/* Generated by Yosys 0.27+30 (git sha1 e56dad56c, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1681341442694/work=/usr/local/src/conda/yosys-0.27_33_ge56dad56c -fdebug-prefix-map=/home/batu/Documents/CFU-Playground/env/conda/envs/cfu-symbiflow=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* \amaranth.hierarchy  = "Cfu" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module Cfu(cmd_ready, cmd_payload_function_id, cmd_payload_inputs_0, cmd_payload_inputs_1, rsp_valid, rsp_ready, rsp_payload_outputs_0, reset, port0_addr, port1_addr, port2_addr, port3_addr, port0_din, port1_din, port2_din, port3_din, clk, rst, cmd_valid);
  reg \$auto$verilog_backend.cc:2097:dump_module$1  = 0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$1 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$10 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$11 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$12 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$13 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$15 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$16 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$17 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$19 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$2 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$20 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$21 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$23 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$24 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$25 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$27 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$3 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$4 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$5 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$6 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$7 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$8 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$9 ;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:185" *)
  input [9:0] cmd_payload_function_id;
  wire [9:0] cmd_payload_function_id;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:186" *)
  input [31:0] cmd_payload_inputs_0;
  wire [31:0] cmd_payload_inputs_0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:187" *)
  input [31:0] cmd_payload_inputs_1;
  wire [31:0] cmd_payload_inputs_1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:183" *)
  output cmd_ready;
  reg cmd_ready;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:182" *)
  input cmd_valid;
  wire cmd_valid;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:246" *)
  reg current_function_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:245" *)
  reg [2:0] current_function_id;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback3_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback3_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback3_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback3_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback4_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback4_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback4_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback4_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback5_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback5_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback5_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback5_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback6_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback6_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback6_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback6_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback7_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback7_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback7_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback7_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:238" *)
  wire [2:0] funct3;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:239" *)
  wire [6:0] funct7;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$28 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$29 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$30 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$31 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$32 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$33 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:213" *)
  wire [63:0] macc_decoded_weights;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire macc_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] macc_funct7;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] macc_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] macc_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] macc_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire macc_start;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] \output ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port0_addr;
  wire [31:0] port0_addr;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port0_din;
  wire [31:0] port0_din;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port1_addr;
  wire [31:0] port1_addr;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port1_din;
  wire [31:0] port1_din;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port2_addr;
  wire [31:0] port2_addr;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port2_din;
  wire [31:0] port2_din;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port3_addr;
  wire [31:0] port3_addr;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port3_din;
  wire [31:0] port3_din;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:191" *)
  input reset;
  wire reset;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:190" *)
  output [31:0] rsp_payload_outputs_0;
  reg [31:0] rsp_payload_outputs_0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:189" *)
  input rsp_ready;
  wire rsp_ready;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:188" *)
  output rsp_valid;
  reg rsp_valid;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  output rst;
  wire rst;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire start;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$14 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$18 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$22 ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$26 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:30" *)
  wire [31:0] store_codebook_clusters;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire store_codebook_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] store_codebook_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] store_codebook_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] store_codebook_output;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire store_codebook_start;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] stored_function_id = 3'h0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] \stored_function_id$next ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] stored_output = 32'd0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] \stored_output$next ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:98" *)
  wire [31:0] weights_clusters;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:99" *)
  wire [63:0] weights_decoded_weights;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire weights_done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] weights_funct7;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] weights_in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] weights_in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire weights_start;
  always @(posedge clk)
    stored_function_id <= \stored_function_id$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    stored_output <= \stored_output$next ;
  fallback3 fallback3 (
    .done(fallback3_done),
    .in0(fallback3_in0),
    .in1(fallback3_in1),
    .\output (fallback3_output)
  );
  fallback4 fallback4 (
    .done(fallback4_done),
    .in0(fallback4_in0),
    .in1(fallback4_in1),
    .\output (fallback4_output)
  );
  fallback5 fallback5 (
    .done(fallback5_done),
    .in0(fallback5_in0),
    .in1(fallback5_in1),
    .\output (fallback5_output)
  );
  fallback6 fallback6 (
    .done(fallback6_done),
    .in0(fallback6_in0),
    .in1(fallback6_in1),
    .\output (fallback6_output)
  );
  fallback7 fallback7 (
    .done(fallback7_done),
    .in0(fallback7_in0),
    .in1(fallback7_in1),
    .\output (fallback7_output)
  );
  macc macc (
    .clk(clk),
    .decoded_weights(macc_decoded_weights),
    .done(macc_done),
    .funct7(macc_funct7),
    .in0(macc_in0),
    .in1(macc_in1),
    .\output (macc_output),
    .rst(rst),
    .start(macc_start)
  );
  store_codebook store_codebook (
    .clk(clk),
    .clusters(store_codebook_clusters),
    .done(store_codebook_done),
    .in0(store_codebook_in0),
    .in1(store_codebook_in1),
    .\output (store_codebook_output),
    .rst(rst),
    .start(store_codebook_start)
  );
  weights weights (
    .clusters(weights_clusters),
    .decoded_weights(weights_decoded_weights),
    .done(weights_done),
    .funct7(weights_funct7),
    .in0(weights_in0),
    .in1(weights_in1),
    .start(weights_start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    current_function_id = 3'h0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          current_function_id = funct3;
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          current_function_id = stored_function_id;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    current_function_done = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:277" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$10 ;
            3'h4:
                current_function_done = \$signal$13 ;
            3'h5:
                current_function_done = \$signal$17 ;
            3'h6:
                current_function_done = \$signal$21 ;
            3'h?:
                current_function_done = \$signal$25 ;
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:289" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$10 ;
            3'h4:
                current_function_done = \$signal$13 ;
            3'h5:
                current_function_done = \$signal$17 ;
            3'h6:
                current_function_done = \$signal$21 ;
            3'h?:
                current_function_done = \$signal$25 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    cmd_ready = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          cmd_ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \stored_function_id$next  = stored_function_id;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                \stored_function_id$next  = cmd_payload_function_id[2:0];
          endcase
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_function_id$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \$signal$2  = 1'h0;
    \$signal$5  = 1'h0;
    \$signal$8  = 1'h0;
    \$signal$11  = 1'h0;
    \$signal$15  = 1'h0;
    \$signal$19  = 1'h0;
    \$signal$23  = 1'h0;
    \$signal$27  = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:282" *)
                casez (current_function_id)
                  3'h0:
                      \$signal$2  = 1'h1;
                  3'h1:
                      \$signal$5  = 1'h1;
                  3'h2:
                      \$signal$8  = 1'h1;
                  3'h3:
                      \$signal$11  = 1'h1;
                  3'h4:
                      \$signal$15  = 1'h1;
                  3'h5:
                      \$signal$19  = 1'h1;
                  3'h6:
                      \$signal$23  = 1'h1;
                  3'h?:
                      \$signal$27  = 1'h1;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    rsp_valid = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      rsp_valid = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                rsp_valid = 1'h1;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_valid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    rsp_payload_outputs_0 = 32'd0;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                      casez (current_function_id)
                        3'h0:
                            rsp_payload_outputs_0 = \$signal ;
                        3'h1:
                            rsp_payload_outputs_0 = \$signal$3 ;
                        3'h2:
                            rsp_payload_outputs_0 = \$signal$6 ;
                        3'h3:
                            rsp_payload_outputs_0 = \$signal$9 ;
                        3'h4:
                            rsp_payload_outputs_0 = \$signal$12 ;
                        3'h5:
                            rsp_payload_outputs_0 = \$signal$16 ;
                        3'h6:
                            rsp_payload_outputs_0 = \$signal$20 ;
                        3'h?:
                            rsp_payload_outputs_0 = \$signal$24 ;
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                casez (current_function_id)
                  3'h0:
                      rsp_payload_outputs_0 = \$signal ;
                  3'h1:
                      rsp_payload_outputs_0 = \$signal$3 ;
                  3'h2:
                      rsp_payload_outputs_0 = \$signal$6 ;
                  3'h3:
                      rsp_payload_outputs_0 = \$signal$9 ;
                  3'h4:
                      rsp_payload_outputs_0 = \$signal$12 ;
                  3'h5:
                      rsp_payload_outputs_0 = \$signal$16 ;
                  3'h6:
                      rsp_payload_outputs_0 = \$signal$20 ;
                  3'h?:
                      rsp_payload_outputs_0 = \$signal$24 ;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_payload_outputs_0 = stored_output;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            \fsm_state$next  = 2'h0;
                        /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            \fsm_state$next  = 2'h1;
                      endcase
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
                  default:
                      \fsm_state$next  = 2'h2;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      \fsm_state$next  = 2'h0;
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      \fsm_state$next  = 2'h1;
                endcase
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
            default:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:296" *)
          casez (rsp_ready)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:296" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \stored_output$next  = stored_output;
    (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            /* empty */;
                        /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            (* full_case = 32'd1 *)
                            (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                            casez (current_function_id)
                              3'h0:
                                  \stored_output$next  = \$signal ;
                              3'h1:
                                  \stored_output$next  = \$signal$3 ;
                              3'h2:
                                  \stored_output$next  = \$signal$6 ;
                              3'h3:
                                  \stored_output$next  = \$signal$9 ;
                              3'h4:
                                  \stored_output$next  = \$signal$12 ;
                              3'h5:
                                  \stored_output$next  = \$signal$16 ;
                              3'h6:
                                  \stored_output$next  = \$signal$20 ;
                              3'h?:
                                  \stored_output$next  = \$signal$24 ;
                            endcase
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      (* full_case = 32'd1 *)
                      (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                      casez (current_function_id)
                        3'h0:
                            \stored_output$next  = \$signal ;
                        3'h1:
                            \stored_output$next  = \$signal$3 ;
                        3'h2:
                            \stored_output$next  = \$signal$6 ;
                        3'h3:
                            \stored_output$next  = \$signal$9 ;
                        3'h4:
                            \stored_output$next  = \$signal$12 ;
                        3'h5:
                            \stored_output$next  = \$signal$16 ;
                        3'h6:
                            \stored_output$next  = \$signal$20 ;
                        3'h?:
                            \stored_output$next  = \$signal$24 ;
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_output$next  = 32'd0;
    endcase
  end
  assign \output  = 32'd0;
  assign rst = reset;
  assign \funct7$33  = funct7;
  assign fallback7_in1 = cmd_payload_inputs_1;
  assign fallback7_in0 = cmd_payload_inputs_0;
  assign \funct7$32  = funct7;
  assign fallback6_in1 = cmd_payload_inputs_1;
  assign fallback6_in0 = cmd_payload_inputs_0;
  assign \funct7$31  = funct7;
  assign fallback5_in1 = cmd_payload_inputs_1;
  assign fallback5_in0 = cmd_payload_inputs_0;
  assign \funct7$30  = funct7;
  assign fallback4_in1 = cmd_payload_inputs_1;
  assign fallback4_in0 = cmd_payload_inputs_0;
  assign \funct7$29  = funct7;
  assign fallback3_in1 = cmd_payload_inputs_1;
  assign fallback3_in0 = cmd_payload_inputs_0;
  assign macc_funct7 = funct7;
  assign macc_in1 = cmd_payload_inputs_1;
  assign macc_in0 = cmd_payload_inputs_0;
  assign weights_funct7 = funct7;
  assign weights_in1 = cmd_payload_inputs_1;
  assign weights_in0 = cmd_payload_inputs_0;
  assign \funct7$28  = funct7;
  assign store_codebook_in1 = cmd_payload_inputs_1;
  assign store_codebook_in0 = cmd_payload_inputs_0;
  assign \start$26  = \$signal$27 ;
  assign \$signal$25  = fallback7_done;
  assign \$signal$24  = fallback7_output;
  assign \start$22  = \$signal$23 ;
  assign \$signal$21  = fallback6_done;
  assign \$signal$20  = fallback6_output;
  assign \start$18  = \$signal$19 ;
  assign \$signal$17  = fallback5_done;
  assign \$signal$16  = fallback5_output;
  assign \start$14  = \$signal$15 ;
  assign \$signal$13  = fallback4_done;
  assign \$signal$12  = fallback4_output;
  assign start = \$signal$11 ;
  assign \$signal$10  = fallback3_done;
  assign \$signal$9  = fallback3_output;
  assign macc_start = \$signal$8 ;
  assign \$signal$7  = macc_done;
  assign \$signal$6  = macc_output;
  assign weights_start = \$signal$5 ;
  assign \$signal$4  = weights_done;
  assign \$signal$3  = 32'd0;
  assign store_codebook_start = \$signal$2 ;
  assign \$signal$1  = store_codebook_done;
  assign \$signal  = store_codebook_output;
  assign macc_decoded_weights = weights_decoded_weights;
  assign weights_clusters = store_codebook_clusters;
  assign funct7 = cmd_payload_function_id[9:3];
  assign funct3 = cmd_payload_function_id[2:0];
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback3" *)
(* generator = "Amaranth" *)
module fallback3(done, in0, in1, \output );
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback4" *)
(* generator = "Amaranth" *)
module fallback4(done, in0, in1, \output );
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback5" *)
(* generator = "Amaranth" *)
module fallback5(done, in0, in1, \output );
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback6" *)
(* generator = "Amaranth" *)
module fallback6(done, in0, in1, \output );
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback7" *)
(* generator = "Amaranth" *)
module fallback7(done, in0, in1, \output );
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.macc" *)
(* generator = "Amaranth" *)
module macc(\output , done, start, in0, in1, funct7, rst, clk, decoded_weights);
  reg \$auto$verilog_backend.cc:2097:dump_module$2  = 0;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/dsl.py:437" *)
  wire \$1 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [32:0] \$10 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [33:0] \$13 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [34:0] \$16 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [35:0] \$19 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:235" *)
  wire [6:0] \$2 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [36:0] \$21 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [32:0] \$24 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [33:0] \$27 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [34:0] \$30 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [35:0] \$33 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [37:0] \$35 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [31:0] \$37 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [15:0] \$38 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [31:0] \$41 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [15:0] \$42 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [31:0] \$45 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [15:0] \$46 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [31:0] \$49 ;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/dsl.py:437" *)
  wire \$5 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [15:0] \$50 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [31:0] \$53 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [15:0] \$54 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [31:0] \$57 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [15:0] \$58 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:242" *)
  wire [6:0] \$6 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [31:0] \$61 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *)
  wire [15:0] \$62 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [31:0] \$65 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *)
  wire [15:0] \$66 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *)
  wire [37:0] \$9 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:223" *)
  wire [31:0] \$signal ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:223" *)
  wire [31:0] \$signal$12 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:223" *)
  wire [31:0] \$signal$15 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:223" *)
  wire [31:0] \$signal$18 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:224" *)
  wire [31:0] \$signal$23 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:224" *)
  wire [31:0] \$signal$26 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:224" *)
  wire [31:0] \$signal$29 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:224" *)
  wire [31:0] \$signal$32 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:214" *)
  reg [31:0] acc = 32'd0;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:214" *)
  reg [31:0] \acc$next ;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:213" *)
  input [63:0] decoded_weights;
  wire [63:0] decoded_weights;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  input [6:0] funct7;
  wire [6:0] funct7;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$10  = $signed(32'd0) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal );
  assign \$13  = $signed(\$10 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$12 );
  assign \$16  = $signed(\$13 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$15 );
  assign \$19  = $signed(\$16 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$18 );
  assign \$21  = $signed(acc) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$19 );
  assign \$24  = $signed(32'd0) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$23 );
  assign \$27  = $signed(\$24 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$26 );
  assign \$30  = $signed(\$27 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$29 );
  assign \$33  = $signed(\$30 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$signal$32 );
  assign \$35  = $signed(\$21 ) + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:243" *) $signed(\$33 );
  assign \$38  = $signed(decoded_weights[7:0]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(in0[7:0]);
  assign \$37  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(\$38 );
  assign \$42  = $signed(decoded_weights[39:32]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(in1[7:0]);
  assign \$41  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(\$42 );
  assign \$46  = $signed(decoded_weights[15:8]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(in0[15:8]);
  assign \$45  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(\$46 );
  assign \$50  = $signed(decoded_weights[47:40]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(in1[15:8]);
  assign \$49  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(\$50 );
  assign \$54  = $signed(decoded_weights[23:16]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(in0[23:16]);
  assign \$53  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(\$54 );
  assign \$58  = $signed(decoded_weights[55:48]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(in1[23:16]);
  assign \$57  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(\$58 );
  assign \$62  = $signed(decoded_weights[31:24]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(in0[31:24]);
  assign \$61  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:230" *) $signed(\$62 );
  assign \$66  = $signed(decoded_weights[63:56]) * (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(in1[31:24]);
  assign \$65  = + (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:231" *) $signed(\$66 );
  always @(posedge clk)
    acc <= \acc$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    \acc$next  = acc;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:235" *)
    casez (\$1 )
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:235" */
      1'h1:
          \acc$next  = 32'd0;
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:238" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:238" */
      1'h1:
          (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:242" *)
          casez (\$5 )
            /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:242" */
            1'h1:
                \acc$next  = \$35 [31:0];
          endcase
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \acc$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    done = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:238" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:238" */
      1'h1:
          done = 1'h1;
    endcase
  end
  assign \$9  = \$35 ;
  assign in1s = in1;
  assign in0s = in0;
  assign \$signal$32  = \$65 ;
  assign \$signal$18  = \$61 ;
  assign \$signal$29  = \$57 ;
  assign \$signal$15  = \$53 ;
  assign \$signal$26  = \$49 ;
  assign \$signal$12  = \$45 ;
  assign \$signal$23  = \$41 ;
  assign \$signal  = \$37 ;
  assign \output  = acc;
  assign { \$2 [6:4], \$2 [2:0] } = 6'h00;
  assign \$2 [3] = funct7[3];
  assign \$1  = funct7[3];
  assign { \$6 [6:5], \$6 [3:0] } = 6'h00;
  assign \$6 [4] = funct7[4];
  assign \$5  = funct7[4];
endmodule

(* \amaranth.hierarchy  = "Cfu.store_codebook" *)
(* generator = "Amaranth" *)
module store_codebook(\output , done, start, in0, in1, rst, clk, clusters);
  reg \$auto$verilog_backend.cc:2097:dump_module$3  = 0;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:30" *)
  output [31:0] clusters;
  reg [31:0] clusters = 32'd0;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:30" *)
  reg [31:0] \clusters$next ;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  always @(posedge clk)
    clusters <= \clusters$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$3 ) begin end
    \clusters$next  = clusters;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" */
      1'h1:
        begin
          \clusters$next [7:0] = in1[7:0];
          \clusters$next [15:8] = in1[15:8];
          \clusters$next [23:16] = in1[23:16];
          \clusters$next [31:24] = in1[31:24];
        end
    endcase
    (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clusters$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$3 ) begin end
    done = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" */
      1'h1:
          done = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$3 ) begin end
    \output  = 32'd0;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:37" */
      1'h1:
          \output  = 32'd1;
    endcase
  end
  assign in1s = in1;
  assign in0s = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.weights" *)
(* generator = "Amaranth" *)
module weights(decoded_weights, done, start, in0, in1, funct7, clusters);
  reg \$auto$verilog_backend.cc:2097:dump_module$4  = 0;
  (* src = "/home/batu/Documents/CFU-Playground/third_party/python/amaranth/amaranth/hdl/dsl.py:437" *)
  wire \$1 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:140" *)
  wire [6:0] \$2 ;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:98" *)
  input [31:0] clusters;
  wire [31:0] clusters;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:99" *)
  output [63:0] decoded_weights;
  reg [63:0] decoded_weights;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  input [6:0] funct7;
  wire [6:0] funct7;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/batu/Documents/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:100" *)
  reg [15:0] weight_codes;
  (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:101" *)
  reg [63:0] weights;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    weights = weights;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:135" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:135" */
      1'h1:
          (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:140" *)
          casez (\$1 )
            /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:140" */
            1'h1:
                weights = { in1, in0 };
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:113" *)
    casez (funct7[1:0])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:114" */
      2'h0:
          weight_codes = weights[15:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:116" */
      2'h1:
          weight_codes = weights[31:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:118" */
      2'h2:
          weight_codes = weights[47:32];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:120" */
      2'h3:
          weight_codes = weights[63:48];
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[1:0])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[7:0] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[7:0] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[7:0] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[7:0] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[3:2])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[15:8] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[15:8] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[15:8] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[15:8] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[5:4])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[23:16] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[23:16] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[23:16] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[23:16] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[7:6])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[31:24] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[31:24] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[31:24] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[31:24] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[9:8])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[39:32] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[39:32] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[39:32] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[39:32] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[11:10])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[47:40] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[47:40] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[47:40] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[47:40] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[13:12])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[55:48] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[55:48] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[55:48] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[55:48] = clusters[31:24];
    endcase
    (* full_case = 32'd1 *)
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:125" *)
    casez (weight_codes[15:14])
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:126" */
      2'h0:
          decoded_weights[63:56] = clusters[7:0];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:128" */
      2'h1:
          decoded_weights[63:56] = clusters[15:8];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:130" */
      2'h2:
          decoded_weights[63:56] = clusters[23:16];
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:132" */
      2'h3:
          decoded_weights[63:56] = clusters[31:24];
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$4 ) begin end
    done = 1'h0;
    (* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:135" *)
    casez (start)
      /* src = "/home/batu/Documents/CFU-Playground/proj/simd/cfu.py:135" */
      1'h1:
          done = 1'h1;
    endcase
  end
  assign in1s = in1;
  assign in0s = in0;
  assign { \$2 [6:3], \$2 [1:0] } = 6'h00;
  assign \$2 [2] = funct7[2];
  assign \$1  = funct7[2];
endmodule
